// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ads.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAd = `-- name: CreateAd :one
INSERT INTO ads (id, created_at, updated_at, title, adtext, notes, company_id, min_exp, german, english, apply_by, time_of_appl, archived)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, created_at, updated_at, title, adtext, notes, company_id, min_exp, german, english, apply_by, time_of_appl, archived
`

type CreateAdParams struct {
	Title      sql.NullString
	Adtext     sql.NullString
	Notes      sql.NullString
	CompanyID  uuid.NullUUID
	MinExp     sql.NullInt32
	German     sql.NullBool
	English    sql.NullBool
	ApplyBy    sql.NullTime
	TimeOfAppl sql.NullTime
	Archived   sql.NullBool
}

func (q *Queries) CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error) {
	row := q.db.QueryRowContext(ctx, createAd,
		arg.Title,
		arg.Adtext,
		arg.Notes,
		arg.CompanyID,
		arg.MinExp,
		arg.German,
		arg.English,
		arg.ApplyBy,
		arg.TimeOfAppl,
		arg.Archived,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Adtext,
		&i.Notes,
		&i.CompanyID,
		&i.MinExp,
		&i.German,
		&i.English,
		&i.ApplyBy,
		&i.TimeOfAppl,
		&i.Archived,
	)
	return i, err
}

const deleteAd = `-- name: DeleteAd :one
DELETE FROM ads
WHERE id = $1
RETURNING id, created_at, updated_at, title, adtext, notes, company_id, min_exp, german, english, apply_by, time_of_appl, archived
`

func (q *Queries) DeleteAd(ctx context.Context, id uuid.UUID) (Ad, error) {
	row := q.db.QueryRowContext(ctx, deleteAd, id)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Adtext,
		&i.Notes,
		&i.CompanyID,
		&i.MinExp,
		&i.German,
		&i.English,
		&i.ApplyBy,
		&i.TimeOfAppl,
		&i.Archived,
	)
	return i, err
}

const getAd = `-- name: GetAd :one
SELECT id, created_at, updated_at, title, adtext, notes, company_id, min_exp, german, english, apply_by, time_of_appl, archived FROM ads
WHERE id = $1
`

func (q *Queries) GetAd(ctx context.Context, id uuid.UUID) (Ad, error) {
	row := q.db.QueryRowContext(ctx, getAd, id)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Adtext,
		&i.Notes,
		&i.CompanyID,
		&i.MinExp,
		&i.German,
		&i.English,
		&i.ApplyBy,
		&i.TimeOfAppl,
		&i.Archived,
	)
	return i, err
}

const getAds = `-- name: GetAds :many
SELECT id, created_at, updated_at, title, adtext, notes, company_id, min_exp, german, english, apply_by, time_of_appl, archived FROM ads
`

func (q *Queries) GetAds(ctx context.Context) ([]Ad, error) {
	rows, err := q.db.QueryContext(ctx, getAds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Adtext,
			&i.Notes,
			&i.CompanyID,
			&i.MinExp,
			&i.German,
			&i.English,
			&i.ApplyBy,
			&i.TimeOfAppl,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAd = `-- name: UpdateAd :one
UPDATE ads
SET updated_at = NOW(), title = $2, adtext = $3, notes = $4, company_id = $5, min_exp = $6, german = $7, english = $8, apply_by = $9, time_of_appl = $10, archived = $11
WHERE id = $1
RETURNING id, created_at, updated_at, title, adtext, notes, company_id, min_exp, german, english, apply_by, time_of_appl, archived
`

type UpdateAdParams struct {
	ID         uuid.UUID
	Title      sql.NullString
	Adtext     sql.NullString
	Notes      sql.NullString
	CompanyID  uuid.NullUUID
	MinExp     sql.NullInt32
	German     sql.NullBool
	English    sql.NullBool
	ApplyBy    sql.NullTime
	TimeOfAppl sql.NullTime
	Archived   sql.NullBool
}

func (q *Queries) UpdateAd(ctx context.Context, arg UpdateAdParams) (Ad, error) {
	row := q.db.QueryRowContext(ctx, updateAd,
		arg.ID,
		arg.Title,
		arg.Adtext,
		arg.Notes,
		arg.CompanyID,
		arg.MinExp,
		arg.German,
		arg.English,
		arg.ApplyBy,
		arg.TimeOfAppl,
		arg.Archived,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Adtext,
		&i.Notes,
		&i.CompanyID,
		&i.MinExp,
		&i.German,
		&i.English,
		&i.ApplyBy,
		&i.TimeOfAppl,
		&i.Archived,
	)
	return i, err
}
