// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (id, created_at, updated_at, notes, commutetime, commutenotes)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, notes, commutetime, commutenotes
`

type CreateCompanyParams struct {
	Notes        sql.NullString
	Commutetime  sql.NullInt32
	Commutenotes sql.NullString
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Notes, arg.Commutetime, arg.Commutenotes)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.Commutetime,
		&i.Commutenotes,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :one
DELETE FROM companies
WHERE id = $1
RETURNING id, created_at, updated_at, notes, commutetime, commutenotes
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRowContext(ctx, deleteCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.Commutetime,
		&i.Commutenotes,
	)
	return i, err
}

const getCompanies = `-- name: GetCompanies :many
SELECT id, created_at, updated_at, notes, commutetime, commutenotes FROM companies
`

func (q *Queries) GetCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, getCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
			&i.Commutetime,
			&i.Commutenotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompany = `-- name: GetCompany :one
SELECT id, created_at, updated_at, notes, commutetime, commutenotes FROM companies
WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.Commutetime,
		&i.Commutenotes,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET updated_at = NOW(), notes = $2, commutetime = $3, commutenotes = $4
WHERE id = $1
RETURNING id, created_at, updated_at, notes, commutetime, commutenotes
`

type UpdateCompanyParams struct {
	ID           uuid.UUID
	Notes        sql.NullString
	Commutetime  sql.NullInt32
	Commutenotes sql.NullString
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany,
		arg.ID,
		arg.Notes,
		arg.Commutetime,
		arg.Commutenotes,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.Commutetime,
		&i.Commutenotes,
	)
	return i, err
}
