// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cvs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCv = `-- name: CreateCv :one
INSERT INTO cvs (id, created_at, updated_at, language, name, notes)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, language, name, notes
`

type CreateCvParams struct {
	Language sql.NullBool
	Name     sql.NullString
	Notes    sql.NullString
}

func (q *Queries) CreateCv(ctx context.Context, arg CreateCvParams) (Cv, error) {
	row := q.db.QueryRowContext(ctx, createCv, arg.Language, arg.Name, arg.Notes)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const deleteCv = `-- name: DeleteCv :one
DELETE FROM cvs
WHERE id = $1
RETURNING id, created_at, updated_at, language, name, notes
`

func (q *Queries) DeleteCv(ctx context.Context, id uuid.UUID) (Cv, error) {
	row := q.db.QueryRowContext(ctx, deleteCv, id)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const getCv = `-- name: GetCv :one
SELECT id, created_at, updated_at, language, name, notes FROM cvs
WHERE id = $1
`

func (q *Queries) GetCv(ctx context.Context, id uuid.UUID) (Cv, error) {
	row := q.db.QueryRowContext(ctx, getCv, id)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const getCvs = `-- name: GetCvs :many
SELECT id, created_at, updated_at, language, name, notes FROM cvs
`

func (q *Queries) GetCvs(ctx context.Context) ([]Cv, error) {
	rows, err := q.db.QueryContext(ctx, getCvs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cv
	for rows.Next() {
		var i Cv
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Language,
			&i.Name,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCv = `-- name: UpdateCv :one
UPDATE cvs
SET updated_at = NOW(), language = $2, name = $3, notes = $4
WHERE id = $1
RETURNING id, created_at, updated_at, language, name, notes
`

type UpdateCvParams struct {
	ID       uuid.UUID
	Language sql.NullBool
	Name     sql.NullString
	Notes    sql.NullString
}

func (q *Queries) UpdateCv(ctx context.Context, arg UpdateCvParams) (Cv, error) {
	row := q.db.QueryRowContext(ctx, updateCv,
		arg.ID,
		arg.Language,
		arg.Name,
		arg.Notes,
	)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
		&i.Name,
		&i.Notes,
	)
	return i, err
}
