// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, created_at, updated_at, occured_at, notes, letter_text, company_id, ad_id, cv_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, occured_at, notes, letter_text, company_id, ad_id, cv_id
`

type CreateEventParams struct {
	OccuredAt  sql.NullTime
	Notes      sql.NullString
	LetterText sql.NullString
	CompanyID  uuid.NullUUID
	AdID       uuid.NullUUID
	CvID       uuid.NullUUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.OccuredAt,
		arg.Notes,
		arg.LetterText,
		arg.CompanyID,
		arg.AdID,
		arg.CvID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccuredAt,
		&i.Notes,
		&i.LetterText,
		&i.CompanyID,
		&i.AdID,
		&i.CvID,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :one
DELETE FROM events
WHERE id = $1
RETURNING id, created_at, updated_at, occured_at, notes, letter_text, company_id, ad_id, cv_id
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, deleteEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccuredAt,
		&i.Notes,
		&i.LetterText,
		&i.CompanyID,
		&i.AdID,
		&i.CvID,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, created_at, updated_at, occured_at, notes, letter_text, company_id, ad_id, cv_id FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccuredAt,
		&i.Notes,
		&i.LetterText,
		&i.CompanyID,
		&i.AdID,
		&i.CvID,
	)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT id, created_at, updated_at, occured_at, notes, letter_text, company_id, ad_id, cv_id FROM events
`

func (q *Queries) GetEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OccuredAt,
			&i.Notes,
			&i.LetterText,
			&i.CompanyID,
			&i.AdID,
			&i.CvID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET updated_at = NOW(), occured_at = $2, notes = $3, letter_text = $4, company_id = $5, ad_id = $6, cv_id = $7
WHERE id = $1
RETURNING id, created_at, updated_at, occured_at, notes, letter_text, company_id, ad_id, cv_id
`

type UpdateEventParams struct {
	ID         uuid.UUID
	OccuredAt  sql.NullTime
	Notes      sql.NullString
	LetterText sql.NullString
	CompanyID  uuid.NullUUID
	AdID       uuid.NullUUID
	CvID       uuid.NullUUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.ID,
		arg.OccuredAt,
		arg.Notes,
		arg.LetterText,
		arg.CompanyID,
		arg.AdID,
		arg.CvID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccuredAt,
		&i.Notes,
		&i.LetterText,
		&i.CompanyID,
		&i.AdID,
		&i.CvID,
	)
	return i, err
}
