// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO list_channels (id, name, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateChannel(ctx context.Context, name sql.NullString) (ListChannel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, name)
	var i ListChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSector = `-- name: CreateSector :one
INSERT INTO list_sectors (id, name, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateSector(ctx context.Context, name sql.NullString) (ListSector, error) {
	row := q.db.QueryRowContext(ctx, createSector, name)
	var i ListSector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO list_sources (id, name, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateSource(ctx context.Context, name sql.NullString) (ListSource, error) {
	row := q.db.QueryRowContext(ctx, createSource, name)
	var i ListSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTool = `-- name: CreateTool :one
INSERT INTO list_tools (id, name, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateTool(ctx context.Context, name sql.NullString) (ListTool, error) {
	row := q.db.QueryRowContext(ctx, createTool, name)
	var i ListTool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :one
DELETE FROM list_channels
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) (ListChannel, error) {
	row := q.db.QueryRowContext(ctx, deleteChannel, id)
	var i ListChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSector = `-- name: DeleteSector :one
DELETE FROM list_sectors
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

func (q *Queries) DeleteSector(ctx context.Context, id uuid.UUID) (ListSector, error) {
	row := q.db.QueryRowContext(ctx, deleteSector, id)
	var i ListSector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :one
DELETE FROM list_sources
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

func (q *Queries) DeleteSource(ctx context.Context, id uuid.UUID) (ListSource, error) {
	row := q.db.QueryRowContext(ctx, deleteSource, id)
	var i ListSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTool = `-- name: DeleteTool :one
DELETE FROM list_tools
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

func (q *Queries) DeleteTool(ctx context.Context, id uuid.UUID) (ListTool, error) {
	row := q.db.QueryRowContext(ctx, deleteTool, id)
	var i ListTool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannels = `-- name: GetChannels :one
SELECT id, name, created_at, updated_at FROM list_channels
`

func (q *Queries) GetChannels(ctx context.Context) (ListChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannels)
	var i ListChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectors = `-- name: GetSectors :one
SELECT id, name, created_at, updated_at FROM list_sectors
`

func (q *Queries) GetSectors(ctx context.Context) (ListSector, error) {
	row := q.db.QueryRowContext(ctx, getSectors)
	var i ListSector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSources = `-- name: GetSources :one
SELECT id, name, created_at, updated_at FROM list_sources
`

func (q *Queries) GetSources(ctx context.Context) (ListSource, error) {
	row := q.db.QueryRowContext(ctx, getSources)
	var i ListSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTools = `-- name: GetTools :one
SELECT id, name, created_at, updated_at FROM list_tools
`

func (q *Queries) GetTools(ctx context.Context) (ListTool, error) {
	row := q.db.QueryRowContext(ctx, getTools)
	var i ListTool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
