// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Ad struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Title      sql.NullString
	Adtext     sql.NullString
	Notes      sql.NullString
	CompanyID  uuid.NullUUID
	MinExp     sql.NullInt32
	German     sql.NullBool
	English    sql.NullBool
	ApplyBy    sql.NullTime
	TimeOfAppl sql.NullTime
	Archived   sql.NullBool
}

type AdsListSource struct {
	ID        uuid.UUID
	AdID      uuid.NullUUID
	SourceID  uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AdsListTool struct {
	ID        uuid.UUID
	AdID      uuid.NullUUID
	ToolID    uuid.NullUUID
	Required  sql.NullBool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CompaniesListSector struct {
	ID        uuid.UUID
	CompanyID uuid.NullUUID
	SectorID  uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Company struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Notes        sql.NullString
	Commutetime  sql.NullInt32
	Commutenotes sql.NullString
}

type Cv struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Language  sql.NullBool
	Name      sql.NullString
	Notes     sql.NullString
}

type Event struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	OccuredAt  sql.NullTime
	Notes      sql.NullString
	LetterText sql.NullString
	CompanyID  uuid.NullUUID
	AdID       uuid.NullUUID
	CvID       uuid.NullUUID
}

type EventsListChannel struct {
	ID        uuid.UUID
	EventID   uuid.NullUUID
	ChannelID uuid.NullUUID
	Required  sql.NullBool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ListChannel struct {
	ID        uuid.UUID
	Name      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ListSector struct {
	ID        uuid.UUID
	Name      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ListSource struct {
	ID        uuid.UUID
	Name      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ListTool struct {
	ID        uuid.UUID
	Name      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
